services:
  windsurfapi:
    build:
      context: .
    image: ghcr.io/wuhao1477/windsurf-to-api-go:latest
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - "3003:3003"
    volumes:
      - ./.docker-data/data:/data
      - ./.docker-data/opt/windsurf:/opt/windsurf
      - ./.docker-data/tmp/windsurf-workspace:/tmp/windsurf-workspace
    restart: unless-stopped

volumes:
  windsurf-ls-data:
  windsurf-workspace:
